language: python
python:
    - "2.7"
install:
    - pip install enum34 dateutils requests junit_xml jenkinsapi beaker-client
script:
    # Make sure all Python files are loadable
    - find -name '*.py' | xargs -l1 -IFILE python -c 'import imp; imp.load_source("", "FILE")'
